# Laboratorium 3 — NumPy
**Autor:** [Julia]

In [1]:
import numpy as np

Ćwiczenie 1: Tworzenie tablic

In [2]:
# 1. Z listy
oceny = np.array([4.0, 3.5, 5.0, 4.5, 3.0, 4.0, 5.0])
print(f"Oceny: {oceny}")
print(f"Typ: {oceny.dtype}")

Oceny: [4.  3.5 5.  4.5 3.  4.  5. ]
Typ: float64


In [3]:
# 2. Zera — 10 elementów
zera = np.zeros(10)
print(f"Zera: {zera}")

Zera: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [4]:
# 3. Jedynki — macierz 3×5
jedynki = np.ones((3, 5))
print(f"Jedynki:\n{jedynki}")

Jedynki:
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [5]:
# 4. Sekwencja od 0 do 100, co 10
dziesiatki = np.arange(0, 101, 10)
print(f"Dziesiątki: {dziesiatki}")

Dziesiątki: [  0  10  20  30  40  50  60  70  80  90 100]


In [6]:
# 5. 7 równomiernych punktów od 0 do 1
ulamki = np.linspace(0, 1, 7)
print(f"Ulamki: {ulamki}")

Ulamki: [0.         0.16666667 0.33333333 0.5        0.66666667 0.83333333
 1.        ]


In [8]:
# 6. 20 losowych ocen od 2 do 5
np.random.seed(42)
losowe_oceny = np.random.randint(2, 6, size=20)
print(f"Losowe oceny: {losowe_oceny}")

Losowe oceny: [4 5 2 4 4 5 2 2 4 3 4 4 4 4 5 2 5 5 5 4]


In [9]:
# Zbadaj tablicę losowych ocen
print(f"shape: {losowe_oceny.shape}")
print(f"ndim: {losowe_oceny.ndim}")
print(f"size: {losowe_oceny.size}")
print(f"dtype: {losowe_oceny.dtype}")

shape: (20,)
ndim: 1
size: 20
dtype: int32


Ćwiczenie 2: Indeksowanie i slicing

Część A — Tablica 1D

In [10]:
miesiace_sprzedaz = np.array([120, 135, 98, 142, 167, 189, 201, 178, 156, 143, 198, 221])
# Indeksy: 0 1 2 3 4 5 6 7 8 9 10 11
# Miesiące: Sty Lut Mar Kwi Maj Cze Lip Sie Wrz Paź Lis Gru

In [12]:
#1. Sprzedaż w styczniu (indeks 0):
print(miesiace_sprzedaz[0])

120


In [13]:
#2. Sprzedaż w grudniu (ostatni element):
print(miesiace_sprzedaz[-1])

221


In [14]:
#3. Sprzedaż w Q1 (styczeń-marzec, indeksy 0-2):
print(miesiace_sprzedaz[0:3])

[120 135  98]


In [17]:
#4. Sprzedaż w Q4 (październik-grudzień, ostatnie 3):
print(miesiace_sprzedaz[-3])

143


In [18]:
#5. Sprzedaż co drugi miesiąc (styczeń, marzec, maj…):
print(miesiace_sprzedaz[::2])

[120  98 167 201 156 198]


In [19]:
#6. Sprzedaż od tyłu (grudzień → styczeń):
print(miesiace_sprzedaz[::-1])

[221 198 143 156 178 201 189 167 142  98 135 120]


Część B — Macierz 2D

In [20]:
# Sprzedaż 4 produktów w 3 kwartałach
dane = np.array([
[120, 145, 167], # Produkt A
[89, 102, 95],
# Produkt B
[234, 267, 289], # Produkt C
[56, 78, 91], # Produkt D
])
produkty = ['Produkt A', 'Produkt B', 'Produkt C', 'Produkt D']
kwartaly = ['Q1', 'Q2', 'Q3']

In [21]:
#1. Sprzedaż Produktu A w Q2 (wiersz 0, kolumna 1):
print(dane[0,1])

145


In [22]:
#2. Cała sprzedaż Produktu C (wiersz 2, wszystkie kolumny):
print(dane[2])

[234 267 289]


In [23]:
#3. Sprzedaż wszystkich produktów w Q1 (wszystkie wiersze, kolumna 0):
print(dane[:,0])

[120  89 234  56]


In [24]:
#4. Sprzedaż Produktów B i C w Q2 i Q3 (wiersze 1-2, kolumny 1-2):
print(dane[1:3,1:3])

[[102  95]
 [267 289]]


Ćwiczenie 3: Operacje wektorowe — analiza biznesowa

Dane

In [25]:
# Produkty w sklepie internetowym
nazwy = ['Laptop', 'Tablet', 'Smartfon', 'Słuchawki', 'Ładowarka',
'Klawiatura', 'Mysz', 'Monitor', 'Kamera', 'Drukarka']
ceny = np.array([3499, 1899, 2499, 349, 89, 249, 129, 1499, 599, 899])
ilosci_magazyn = np.array([15, 42, 78, 156, 312, 89, 201, 23, 45, 34])
oceny_klientow = np.array([4.7, 4.2, 4.5, 4.8, 3.9, 4.1, 4.3, 4.6, 3.8, 3.5])

Zadanie 1: Podstawowe statystyki cenowe

In [28]:
# Średnia cena, najdroższy produkt, najtańszy produkt
# Podpowiedzi: .mean(), .max(), .min(), .argmax(), .argmin()
srednia_cena = ceny.mean()
najdrozszy_produkt = ceny.argmax()
najtanszy_produkt = ceny.argmin()
print(srednia_cena)
print(nazwy[najdrozszy_produkt], ceny[najdrozszy_produkt])
print(nazwy[najtanszy_produkt], ceny[najtanszy_produkt])

1171.0
Laptop 3499
Ładowarka 89


Średnia cena produktów wynosi 1171zł. Najdroższy produkt to laptop (3499zł) natomiast najtańszy to ładowarka (89zł).

Zadanie 2: Wartość magazynu

In [29]:
# Oblicz wartość każdego produktu (cena × ilość) i łączną wartość magazynu
# Podpowiedź: mnożenie tablic element-wise
wartosci = ceny * ilosci_magazyn
print(wartosci)
print(wartosci.sum())

[ 52485  79758 194922  54444  27768  22161  25929  34477  26955  30566]
549465


Wartości produktów: 52485zł, 79758zł, 194922zł, 54444zł, 27768zł, 22161zł,  25929zł, 34477zł, 26955zł, 30566zł. 

Łączna wartóść magazynu: 549465zł.

Zadanie 3: Analiza cenowa

In [31]:
# Stworz array z cenami po rabacie 15% (promocja świąteczna)
# Stworz array z cenami po uwzględnieniu VAT 23%
# Ile produktów kosztuje powyżej 1000 zł?
# Podpowiedź: rabat = ceny * 0.85, VAT = ceny * 1.23, zliczanie: (warunek).sum()
rabat = ceny * 0.85
vat = ceny * 1.23
powyzej1000 = ceny > 1000
print(rabat)
print(vat)
print(powyzej1000.sum())

[2974.15 1614.15 2124.15  296.65   75.65  211.65  109.65 1274.15  509.15
  764.15]
[4303.77 2335.77 3073.77  429.27  109.47  306.27  158.67 1843.77  736.77
 1105.77]
4


Ceny produktów objętnych promocją świąteczną (-15%): 2974.15zł, 1614.15zł, 2124.15zł, 296.65zł, 75.65zł, 211.65zł, 109.65zł, 1274.15zł, 509.15zł, 764.15zł.

Ceny produktów po uwzględnieniu VAT(23%): 4303.77zł, 2335.77zł, 3073.77zł, 429.27zł, 109.47zł, 306.27zł, 158.67zł, 1843.77zł, 736.77zł, 1105.77zł.

Ilość produktów, których cena wynosi więcej niż 1000zł jest równa 4.


Zadanie 4: Filtrowanie

In [33]:
# Produkty z oceną >= 4.5 — nazwy i ceny
# Produkty poniżej 200 zł — nazwy i ilości w magazynie
# Podpowiedź: maska = oceny_klientow >= 4.5, potem ceny[maska]
# Uwaga: nazwy to zwykła lista — zamień ją na np.array(nazwy), żeby użyć maski
maska = oceny_klientow >= 4.5
nazwy = np.array(nazwy)
print("Produkty z oceną >= 4.5: ", nazwy[maska], ceny[maska])

ponizej200 = ceny < 200
print("Produkty poniżej 200zł :", nazwy[ponizej200], ilosci_magazyn[ponizej200])

Produkty z oceną >= 4.5:  ['Laptop' 'Smartfon' 'Słuchawki' 'Monitor'] [3499 2499  349 1499]
Produkty poniżej 200zł : ['Ładowarka' 'Mysz'] [312 201]


Produkty z oceną >= 4.5: Laptop (3499zł), Smartfon(2499zł), Słuchawki(349zł),Monitor(1499zł).

Produnkty, których cena wynosi mniej niż 200zł: Ładowarka(312szt.), Mysz(201szt.)

Zadanie 5: Analiza zapasów

In [37]:
# Produkty z niskim stanem magazynowym (< 30 szt.) — nazwy
# Łączna wartość tych produktów
# Ile % całego magazynu stanowią?
# Podpowiedź: wartosci = ceny * ilosci_magazyn, potem filtruj maską
wartosci = ceny * ilosci_magazyn
maska = ilosci_magazyn < 30
wartosc_niski = wartosci[maska].sum()
procent = wartosc_niski / wartosci.sum() * 100

print(nazwy[maska])
print(wartosc_niski)
print(procent)

['Laptop' 'Monitor']
86962
15.826667758637946


Produkty z niskim stanem magazynowym (<30szt.): Laptop, Monitor.

Łączna watość tych produktów wynosi: 86962zł.

Podane produkty stanowią ok.15.83% całego magazynu

Zadanie 6 (bonus): Analiza korelacji cena–ocena

In [38]:
# Które produkty są "okazją" — ocena >= 4.5 i cena < 1000 zł? Wypisz nazwy i ceny.
# Jaka jest średnia cena produktów z oceną >= 4.0 vs < 4.0?
# Podpowiedź: łączenie warunków: (warunek1) & (warunek2)
okazja = (oceny_klientow >= 4.5) & (ceny < 1000)
print(nazwy[okazja], ceny[okazja])

oceny_dobre = oceny_klientow >= 4.0
oceny_slabe = oceny_klientow < 4.0
srednia_dobre = ceny[oceny_dobre].mean()
srednia_slabe = ceny[oceny_slabe].mean()
print(srednia_dobre)
print(srednia_slabe)

['Słuchawki'] [349]
1446.142857142857
529.0


Okazja: Słuchawki 

Cena: 349zł

Średnia cena produktów z oceną >= 4.0 wynosi ok.1446.14zł.

Średnia cena produktów z oceną < 4.0 wynosi 529zł.

Ćwiczenie 4: Benchmark — lista vs NumPy

In [39]:
#Benchmark
import time

In [40]:
# Przygotowanie danych
rozmiar = 1_000_000
lista = list(range(rozmiar))
tablica = np.array(lista)

In [41]:
# Test 1: Pomnóż przez 2
start = time.perf_counter()
wynik_lista = [x * 2 for x in lista]
czas_lista = time.perf_counter()- start
start = time.perf_counter()
wynik_numpy = tablica * 2
czas_numpy = time.perf_counter()- start
print(f"=== Mnożenie ×2 ({rozmiar:,} elementów) ===")
print(f"Lista: {czas_lista*1000:.1f} ms")
print(f"NumPy: {czas_numpy*1000:.1f} ms")
print(f"NumPy jest {czas_lista/czas_numpy:.0f}× szybszy!")

=== Mnożenie ×2 (1,000,000 elementów) ===
Lista: 112.8 ms
NumPy: 3.4 ms
NumPy jest 33× szybszy!


In [42]:
# Test 2: Suma
start = time.perf_counter()
suma_lista = sum(lista)
czas_lista = time.perf_counter()- start
start = time.perf_counter()
suma_numpy = tablica.sum()
czas_numpy = time.perf_counter()- start
print(f"\n=== Suma ({rozmiar:,} elementów) ===")
print(f"Lista: {czas_lista*1000:.1f} ms")
print(f"NumPy: {czas_numpy*1000:.1f} ms")
print(f"NumPy jest {czas_lista/czas_numpy:.0f}× szybszy!")


=== Suma (1,000,000 elementów) ===
Lista: 32.2 ms
NumPy: 2.2 ms
NumPy jest 15× szybszy!


In [43]:
# Test 3: Filtrowanie (elementy > 500000)
start = time.perf_counter()
filtr_lista = [x for x in lista if x > 500000]
czas_lista = time.perf_counter()- start
start = time.perf_counter()
filtr_numpy = tablica[tablica > 500000]
czas_numpy = time.perf_counter()- start
print(f"\n=== Filtrowanie > 500k ({rozmiar:,} elementów) ===")
print(f"Lista: {czas_lista*1000:.1f} ms")
print(f"NumPy: {czas_numpy*1000:.1f} ms")
print(f"NumPy jest {czas_lista/czas_numpy:.0f}× szybszy!")


=== Filtrowanie > 500k (1,000,000 elementów) ===
Lista: 79.7 ms
NumPy: 3.0 ms
NumPy jest 27× szybszy!


## Wnioski z benchmarku
- NumPy jest **33×** szybszy w mnożeniu
- NumPy jest **15×** szybszy w sumowaniu
- NumPy jest **27×** szybszy w filtrowaniu
- Wniosek: przy dużych danych **zawsze** używaj NumPy zamiast list