# Laboratorium 3 — NumPy
**Autor:** [Julia]

In [7]:
import numpy as np


In [8]:
# 1. Z listy
oceny = np.array([4.0, 3.5, 5.0, 4.5, 3.0, 4.0, 5.0])
print(f"Oceny: {oceny}")
print(f"Typ: {oceny.dtype}")

Oceny: [4.  3.5 5.  4.5 3.  4.  5. ]
Typ: float64


In [9]:
# 2. Zera — 10 elementów
zera = np.zeros(10)
print(f"Zera: {zera}")

Zera: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [10]:
# 3. Jedynki — macierz 3×5
jedynki = np.ones((3, 5))
print(f"Jedynki:\n{jedynki}")

Jedynki:
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [11]:
# 4. Sekwencja od 0 do 100, co 10
dziesiatki = np.arange(0, 101, 10)
print(f"Dziesiątki: {dziesiatki}")

Dziesiątki: [  0  10  20  30  40  50  60  70  80  90 100]


In [12]:
# 5. 7 równomiernych punktów od 0 do 1
ulamki = np.linspace(0, 1, 7)
print(f"Ulamki: {ulamki}")

Ulamki: [0.         0.16666667 0.33333333 0.5        0.66666667 0.83333333
 1.        ]


In [13]:
# 6. 20 losowych ocen od 2 do 5
np.random.seed(42)
losowe_oceny = np.random.randint(2, 6, size=20)
print(f"Losowe oceny: {losowe_oceny}")

Losowe oceny: [4 5 2 4 4 5 2 2 4 3 4 4 4 4 5 2 5 5 5 4]


In [14]:
# Zbadaj tablicę losowych ocen
print(f"shape: {losowe_oceny.shape}")
print(f"ndim: {losowe_oceny.ndim}")
print(f"size: {losowe_oceny.size}")
print(f"dtype: {losowe_oceny.dtype}")

shape: (20,)
ndim: 1
size: 20
dtype: int32


#Część A — Tablica 1D

In [15]:
miesiace_sprzedaz = np.array([120, 135, 98, 142, 167, 189, 201, 178, 156, 143, 198, 221])
# Indeksy: 
# Miesiące: 0 1 2 3 4 5 6 7 8 9 10 11
# Miesiące: Sty Lut Mar Kwi Maj Cze Lip Sie Wrz Paź Lis Gru

1. Sprzedaż w styczniu (indeks 0):

In [16]:
print(miesiace_sprzedaz[0])

120


2. Sprzedaż w grudniu (ostatni element):

In [17]:
print(miesiace_sprzedaz[-1])

221


3. Sprzedaż w Q1 (styczeń-marzec, indeksy 0-2):

In [18]:
print(miesiace_sprzedaz[0:3])

[120 135  98]


4. Sprzedaż w Q4 (październik-grudzień, ostatnie 3):

In [19]:
print(miesiace_sprzedaz[-3:])

[143 198 221]


5. Sprzedaż co drugi miesiąc (styczeń, marzec, maj…):

In [20]:
print(miesiace_sprzedaz[::2])

[120  98 167 201 156 198]


6. Sprzedaż od tyłu (grudzień → styczeń):

In [21]:
print(miesiace_sprzedaz[::-1])

[221 198 143 156 178 201 189 167 142  98 135 120]


#Część B — Macierz 2D

In [22]:
# Sprzedaż 4 produktów w 3 kwartałach
dane = np.array([
[120, 145, 167], # Produkt A
[89, 102, 95], # Produkt B
[234, 267, 289], # Produkt C
[56, 78, 91], # Produkt D
])
produkty = ['Produkt A', 'Produkt B', 'Produkt C', 'Produkt D']
kwartaly = ['Q1', 'Q2', 'Q3']

1. Sprzedaż Produktu A w Q2 (wiersz 0, kolumna 1):

In [23]:
print(dane[0, 1])

145


2. Cała sprzedaż Produktu C (wiersz 2, wszystkie kolumny):

In [24]:
print(dane[2, :])

[234 267 289]


3. Sprzedaż wszystkich produktów w Q1 (wszystkie wiersze, kolumna 0):

In [25]:
print(dane[:, 0])

[120  89 234  56]


4. Sprzedaż Produktów B i C w Q2 i Q3 (wiersze 1-2, kolumny 1-2):

In [26]:
print(dane[1:3, 1:3])

[[102  95]
 [267 289]]


#Dane

In [27]:
# Produkty w sklepie internetowym
nazwy = ['Laptop', 'Tablet', 'Smartfon', 'Słuchawki', 'Ładowarka',
'Klawiatura', 'Mysz', 'Monitor', 'Kamera', 'Drukarka']
ceny = np.array([3499, 1899, 2499, 349, 89, 249, 129, 1499, 599, 899])
ilosci_magazyn = np.array([15, 42, 78, 156, 312, 89, 201, 23, 45, 34])
oceny_klientow = np.array([4.7, 4.2, 4.5, 4.8, 3.9, 4.1, 4.3, 4.6, 3.8, 3.5])

Zadanie 1: Podstawowe statystyki cenowe

In [28]:
# Średnia cena, najdroższy produkt, najtańszy produkt
# Podpowiedzi: .mean(), .max(), .min(), .argmax(), .argmin()

średnia_cena = ceny.mean()
najdroższy_produkt = ceny.max()
najtańszy_produkt = ceny.min()

print(średnia_cena)
print(najdroższy_produkt)
print(najtańszy_produkt)

1171.0
3499
89


Zadanie 2: Wartość magazynu

In [30]:
# Oblicz wartość każdego produktu (cena × ilość) i łączną wartość magazynu
# Podpowiedź: mnożenie tablic element-wise

wszystkie_produkty = ceny * ilosci_magazyn
magazyn = wszystkie_produkty.sum()

print(wszystkie_produkty)
print(magazyn)

[ 52485  79758 194922  54444  27768  22161  25929  34477  26955  30566]
549465


Zadanie 3: Analiza cenowa

In [32]:
# Stworz array z cenami po rabacie 15% (promocja świąteczna)
# Stworz array z cenami po uwzględnieniu VAT 23%
# Ile produktów kosztuje powyżej 1000 zł?
# Podpowiedź: rabat = ceny * 0.85, VAT = ceny * 1.23, zliczanie: (warunek).sum()
rabat = ceny * 0.85
vat = ceny * 1.23
zliczanie = (ceny > 1000).sum()

print(rabat)
print(vat)
print(zliczanie)

[2974.15 1614.15 2124.15  296.65   75.65  211.65  109.65 1274.15  509.15
  764.15]
[4303.77 2335.77 3073.77  429.27  109.47  306.27  158.67 1843.77  736.77
 1105.77]
4


Zadanie 4: Filtrowanie

In [40]:
# Produkty z oceną >= 4.5 — nazwy i ceny
# Produkty poniżej 200 zł — nazwy i ilości w magazynie
# Podpowiedź: maska = oceny_klientow >= 4.5, potem ceny[maska]
# Uwaga: nazwy to zwykła lista — zamień ją na np.array(nazwy), żeby użyć maski
nazwy = np.array(nazwy)
maska_oceny = oceny_klientow >= 4.5
print('Nazwa:',nazwy[maska_oceny])
print("Ceny:", ceny[maska_oceny])

maska_ceny = ceny < 200
print('Nazwa:', nazwy[maska_ceny])
print('Ilość w magazynie:', ilosci_magazyn[maska_ceny])






Nazwa: ['Laptop' 'Smartfon' 'Słuchawki' 'Monitor']
Ceny: [3499 2499  349 1499]
Nazwa: ['Ładowarka' 'Mysz']
Ilość w magazynie: [312 201]


Zadanie 5: Analiza zapasów

In [ ]:
# Produkty z niskim stanem magazynowym (< 30 szt.) — nazwy
# Łączna wartość tych produktów
# Ile % całego magazynu stanowią?
# Podpowiedź: wartosci = ceny * ilosci_magazyn, potem filtruj maską
niski_stan = ilosci_magazyn < 30
print("Produkty z niskim stanem magazynowym:", nazwy[niski_stan])
print("Ilość:", ilosci_magazyn[niski_stan])

wartosi = ceny * ilosci_magazyn


Produkty z niskim stanem magazynowym: ['Laptop' 'Monitor']
Ilość: [15 23]


Zadanie 6 (bonus): Analiza korelacji cena–ocena

In [ ]:
# Które produkty są "okazją" — ocena >= 4.5 i cena < 1000 zł? Wypisz nazwy i ceny.
# Jaka jest średnia cena produktów z oceną >= 4.0 vs < 4.0?
# Podpowiedź: łączenie warunków: (warunek1) & (warunek2)

Ćwiczenie 4: Benchmark — lista vs NumPy (15 min)

In [ ]:
#Benchmark
import time

In [ ]:
# Przygotowanie danych
rozmiar = 1_000_000
lista = list(range(rozmiar))
tablica = np.array(lista)

In [ ]:
# Test 1: Pomnóż przez 2
start = time.perf_counter()
wynik_lista = [x * 2 for x in lista]
czas_lista = time.perf_counter()- start
start = time.perf_counter()
wynik_numpy = tablica * 2
czas_numpy = time.perf_counter()- start
print(f"=== Mnożenie ×2 ({rozmiar:,} elementów) ===")
print(f"Lista: {czas_lista*1000:.1f} ms")
print(f"NumPy: {czas_numpy*1000:.1f} ms")
print(f"NumPy jest {czas_lista/czas_numpy:.0f}× szybszy!")

In [ ]:
# Test 2: Suma
start = time.perf_counter()
suma_lista = sum(lista)
czas_lista = time.perf_counter()- start
start = time.perf_counter()
suma_numpy = tablica.sum()
czas_numpy = time.perf_counter()- start
print(f"\n=== Suma ({rozmiar:,} elementów) ===")
print(f"Lista: {czas_lista*1000:.1f} ms")
print(f"NumPy: {czas_numpy*1000:.1f} ms")
print(f"NumPy jest {czas_lista/czas_numpy:.0f}× szybszy!")

In [ ]:
# Test 3: Filtrowanie (elementy > 500000)
start = time.perf_counter()
filtr_lista = [x for x in lista if x > 500000]
czas_lista = time.perf_counter()- start
start = time.perf_counter()
filtr_numpy = tablica[tablica > 500000]
czas_numpy = time.perf_counter()- start
print(f"\n=== Filtrowanie > 500k ({rozmiar:,} elementów) ===")
print(f"Lista: {czas_lista*1000:.1f} ms")
print(f"NumPy: {czas_numpy*1000:.1f} ms")
print(f"NumPy jest {czas_lista/czas_numpy:.0f}× szybszy!")

## Wnioski z benchmarku
- NumPy jest **...×** szybszy w mnożeniu
- NumPy jest **...×** szybszy w sumowaniu
- NumPy jest **...×** szybszy w filtrowaniu
- Wniosek: przy dużych danych **zawsze** używaj NumPy zamiast list

Ćwiczenie 5: Commit na GitHub (5 min)